### PR TITLE
Mention okapi-curl-env

### PR DESCRIPTION
**Pull request by julianladisch**

### CODE REVIEW

**Review by adamdickmeiss — COMMENTED** [review]
What happened to https://github.com/MikeTaylor/okapi-curl @MikeTaylor  ?? Don't we mention that already?

**Comment by MikeTaylor** [comment]
Honestly, I think @wafschneider's `okapi-curl-env` is a mistake. Instead of adding evironment variable support to the existing `okapi-curl`, he forked it. I lament that both now exist and the Okapi documentation has to either link to both, or choose which one it links to.

@wafschneider What would stop you from just merging your changes back into `okapi-curl` and deleting the fork?

**Comment by julianladisch** [comment]
@MikeTaylor What would stop you from just moving https://github.com/MikeTaylor/okapi-curl to https://github.com/folio-org/okapi-curl ?

**Comment by MikeTaylor** [comment]
@julianladisch I put it in my own GitHub area because I needed to use it and just wanted it to be done, without wanting to wrangle with all the FOLIO bureaucracy. If someone wants to move it into `folio-org` — and take on responsibility for whatever obligations come with that — they are quite welcome.

**Comment by julianladisch** [comment]
This pull request is blocked by https://issues.folio.org/browse/FOLIO-3193 "DECISION: In which repository should okapi-curl live?"

**Comment by wafschneider** [comment]
I hate to make @MikeTaylor lament something. I will look at unifying the two tools.

**Comment by wafschneider** [comment]
I have offered a PR to https://github.com/MikeTaylor/okapi-curl : https://github.com/MikeTaylor/okapi-curl/pull/1

**Comment by MikeTaylor** [comment]
And I have merged it!

**Comment by adamdickmeiss** [comment]
Close this without merge?

**Comment by MikeTaylor** [comment]
Sounds right to me, @adamdickmeiss. And we can close https://issues.folio.org/browse/FOLIO-3193

**Pull request closed without merging**
