### PR TITLE
Refer to correct service in login discussion

### PR DESCRIPTION
**Pull request by MikeTaylor**
@adamdickmeiss I think I stopped and fixed a thinko, but please check that I've not misunderstood, and introduced one instead!

### CODE REVIEW

**Review by adamdickmeiss — COMMENTED** [review]
There's no mod-login in Okapi guide (no example module as part of Okapi). It's an auth module which does both authorization and authentication.

**Comment by MikeTaylor** [comment]
Then what _does_ mod-login do, if not give you a token in exchange for your credentials?

Or are you saying that the scenario outlined in the Guide is different from the one implemented in FOLIO?

**Comment by adamdickmeiss** [comment]
> Then what _does_ mod-login do, if not give you a token in exchange for your credentials?
> 
> Or are you saying that the scenario outlined in the Guide is different from the one implemented in FOLIO?

mod-login is responsible for that. But mod-login is *not* part of Okapi. Okapi does not mention the FOLIO system. All examples are based on 3 test modules that's part of the distribution.

**Comment by MikeTaylor** [comment]
Ah, I see: the example are not FOLIO examples.

I guess that's OK. But I bet I won't be the last person to be confused by this.

**Comment by adamdickmeiss** [comment]
> Ah, I see: the example are not FOLIO examples.
> 
> I guess that's OK. But I bet I won't be the last person to be confused by this.

The MD of that example module says it all: https://github.com/folio-org/okapi/blob/master/okapi-test-auth-module/descriptors/ModuleDescriptor-template.json

**Comment by MikeTaylor** [comment]
OK, we'll leave this as it is.

**Pull request closed without merging**
